# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('pollution', models.BooleanField()),
                ('temp', models.IntegerField(default=0)),
                ('humid', models.IntegerField(default=0)),
                ('flood', models.BooleanField()),
                ('eeg', models.IntegerField(default=0)),
                ('hr', models.IntegerField(default=0)),
                ('distance', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
            ],
        ),
    ]
