# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20170325_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='flood',
            field=models.IntegerField(default=0),
        ),
    ]
