# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20170325_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='eeg',
            new_name='attention',
        ),
        migrations.AddField(
            model_name='item',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='lng',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='meditation',
            field=models.IntegerField(default=0),
        ),
    ]
