# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_auto_20170325_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='driver_id',
            field=models.IntegerField(default=1),
        ),
    ]
