# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_item_driver_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rest',
            field=models.IntegerField(default=0),
        ),
    ]
